# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Keyple support
    url: '/keyple-support/'
    weight: 10

  - name: Introduction
    parent: Keyple support
    url: '/keyple-support/introduction/'
    weight: 10
  - name: Ticketing demo
    parent: Keyple support
    url: '/keyple-support/ticketing-demo/'
    weight: 20
  - name: Reader plugins
    parent: Keyple support
    url: '/keyple-support/reader-plugins/'
    weight: 30


  - name: Assistance tools
    url: '/assistance-tools/'
    weight: 20

  - name: Card configuration audit
    parent: Assistance tools
    url: '/assistance-tools/card-configuration-audit/'
    weight: 10
  - name: Basic Legacy SAM personalizer
    parent: Assistance tools
    url: '/assistance-tools/basic-legacysam-personalizer/'
    weight: 20
  - name: Basic card personalizer
    parent: Assistance tools
    url: '/assistance-tools/basic-card-personalizer/'
    weight: 30